### ISSUE TITLE
Adding Face Counter Feature

### ISSUE THREAD

**Issue by Loopex2019** [rishab2113/firebase_mlkit_language#28]
Hi . I know it's not the package Mission for adding Face Counter , ('These are just little Points in the Face detected by Face LandMarks'), but my wish is to add this Feature as a second Feature beside 
the Translation Feature. I searched in lots of Packages by using the Face Counter but i couldn't
find it, i just found it in one Package but it's just for Android plus that i have to remove some pre-installed Packages to make it work. But thanks for your awesome Work about the Translation Feature.

**Comment by rishabnayak** [comment]
Hi, thanks for reaching out! The face counter feature sounds like something that would be added to the firebase_ml_vision package. I can try working on it, do watch for updates on that repository!

**Comment by Loopex2019** [comment]
Okay thanks
