### ISSUE TITLE
[BUG]  Do not support AndroidX?

### ISSUE THREAD

**Issue by XinyueZ** [rishab2113/firebase_mlkit_language#29]
I get the exception while running
```
 flutter build apk --debug
```
There will be output with errors like below:
```
pub-cache/hosted/pub.dartlang.org/firebase_mlkit_language-1.1.2/android/src/main/java/io/flutter/plugins/firebase_mlkit_language/LanguageIdentifier.java:3: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;  
```

Would you mind updating the library for `AndroidX Jetpack `stuff?

**Comment by rishabnayak** [comment]
Thanks for the PR! I’ll take a look and update ASAP!

**Comment by VibhutiBansal-11** [comment]
Is the library updated, because I still face the same issue. Thanks for any help !
